### ISSUE TITLE
Math selection issue

### ISSUE THREAD

**Issue by lzhaxi** [18nshinagawa/notes#91]
When not in math, cannot select other math equations. In order to go back and edit, you would have to open a new math equation then click on the old math equation.

**Comment by lzhaxi** [comment]
Then when you go back and edit it, a copy of the same math equation is made without editing the original math equation

**Comment by 18nshinagawa** [comment]
this one is really bad lol sorry

**Comment by 18nshinagawa** [comment]
big issue

maybe it is because `mouseDown` is interfering with `click`.

**Comment by 18nshinagawa** [comment]
i think this is already fixed in the newest one but i guess the current version is some intermediate in which it was broken

**Comment by lzhaxi** [comment]
It's still broken, you can use your arrow keys to go back through math which causes lots of issues

**Comment by 18nshinagawa** [comment]
In what situation? it seems to be more specific

i tested:

1. math at end of line, pressing left arrow key from next line
2. math with text on both sides
3,. math at beginning of line, pressing arrow key right from previous line

and it seems to at least work for all cases
